// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['DEV_WEB_APIKEY']!,
    appId: dotenv.env['DEV_WEB_APPID']!,
    messagingSenderId: dotenv.env['DEV_MESSAGINGSENDERID']!,
    projectId: 'lovehue-dev',
    authDomain: 'lovehue-dev.firebaseapp.com',
    storageBucket: 'lovehue-dev.appspot.com',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['DEV_ANDROID_APIKEY']!,
    appId: dotenv.env['DEV_ANDROID_APPID']!,
    messagingSenderId: dotenv.env['DEV_MESSAGINGSENDERID']!,
    projectId: 'lovehue-dev',
    storageBucket: 'lovehue-dev.appspot.com',
  );
}
