name: auto-merge-dependabot

on:
    pull_request:
        branches:
            - package-updates

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

permissions: # added using https://github.com/step-security/secure-workflows
    contents: read

jobs:
    auto-merge:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
            - uses: ahmadnassri/action-dependabot-auto-merge@45fc124d949b19b6b8bf6645b6c9d55f4f9ac61a # v2.6.6
              with:
                  github-token: ${{ secrets.AUTO_MERGE_TOKEN }}
                  target: minor
