name: Auto reviews release
on: pull_request
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@b40d6c9ed2fa10c9a2749eca7eb004418a705501
        if: github.actor == 'clukes'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
