name: Auto reviews release
on:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v2
        if: github.actor == 'clukes'
        with:
          github-token: ${{ secrets.AUTOREVIEWPAT }}
