name: auto-merge-dependabot

on:
  pull_request:
    branches:
      - development

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
      - uses: ahmadnassri/action-dependabot-auto-merge@5d98f10d910782d0bb431fc03ae26532543ae184
        with:
          github-token: ${{ secrets.AUTO_MERGE_TOKEN }}
          target: minor
