name: Integration Tests
on:
    push:
        branches:
            - main
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    # ios:
    #   # Creates a build matrix for your jobs. You can define different variations of an environment to run each job
    #   strategy:
    #     matrix:
    #       device:
    #         # The available simulators are listed by the "xcrun xctrace list devices" command
    #         - "iPhone 11 Simulator (15.2)" # the name of the simulator could be different depending on the macos version you are using
    #     # if one of the jobs in the matrix expansion fails, the rest of the jobs will be cancelled
    #     fail-fast: true
    #   runs-on: macos-11 # or macos-latest if you prefer, but be aware that the available simulators could be different if you run a different version
    #   steps:
    #     - name: "List all simulators"
    #       run: "xcrun xctrace list devices"
    #     - name: "Start Simulator"
    #       # the command "xcrun simctl boot" expects a device identifier
    #       # the assignment of the UDID variable consists of retrieving the ID of the simulator
    #       # by extracting it from the command "xcrun xctrace list devices"
    #       run: |
    #         UDID=$(xcrun xctrace list devices | grep "^${{ matrix.device }}" | awk '{gsub(/[()]/,""); print $NF}')
    #         echo $UDID
    #         xcrun simctl boot "${UDID:?No Simulator with this name found}"
    #     - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    #     # Set up Flutter.
    #     - name: Get Flutter version
    #       id: get-flutter-version
    #       uses: zgosalvez/github-actions-get-flutter-version-env@7fddf5259c22045dea8dc2f098f494bbd3ca2749 # v2.0.16
    #     - name: Clone Flutter repository with stable channel
    #       uses: subosito/flutter-action@dbf1fa04f4d2e52c33185153d06cdb5443aa189d
    #       with:
    #       cache: true
    #       channel: "stable"
    #       flutter-version: ${{ steps.get-flutter-version.outputs.version }}
    #     - name: Install Flutter dependencies
    #       run: flutter pub get
    #     - name: Run integration tests
    #       run: flutter test integration_test --verbose

    android:
        runs-on: macos-latest
        strategy:
            matrix:
                api-level: [33]
                target: [google_apis]
                arch: [x86_64]
            fail-fast: true
        steps:
            - name: Checkout code
              uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
            - name: Emulator cache
              uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
              with:
                  path: ~/.cache/firebase/emulators
                  key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}
            - name: Setup java
              uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
              with:
                  distribution: "temurin"
                  java-version: "17"
            - name: Install Firebase Emulator Suite
              run: npm install -g firebase-tools
            - name: Start firebase emulator
              run: firebase emulators:start &
            # Set up Flutter.
            - name: Get Flutter version
              id: get-flutter-version
              uses: zgosalvez/github-actions-get-flutter-version-env@7fddf5259c22045dea8dc2f098f494bbd3ca2749 # v2.0.16
            - name: Setup Flutter SDK
              uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
              with:
                  cache: true
                  flutter-version: ${{ steps.get-flutter-version.outputs.version }}
                  channel: stable
            - name: Install Flutter dependencies
              run: flutter pub get
            - name: Gradle cache
              uses: gradle/gradle-build-action@915a66c096a03101667f9df2e56c9efef558b165 # v2.6.1
            - name: AVD cache
              uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
              id: avd-cache
              with:
                  path: |
                      ~/.android/avd/*
                      ~/.android/adb*
                  key: avd-${{ matrix.api-level }}
            - name: Create AVD and generate snapshot for caching
              if: steps.avd-cache.outputs.cache-hit != 'true'
              uses: reactivecircus/android-emulator-runner@d94c3fbe4fe6a29e4a5ba47c12fb47677c73656b # v2.28.0
              with:
                  api-level: ${{ matrix.api-level }}
                  target: ${{ matrix.target }}
                  arch: ${{ matrix.arch }}
                  force-avd-creation: false
                  emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
                  disable-animations: false
                  script: echo "Generated AVD snapshot for caching."
            - name: Run tests
              uses: Wandalen/wretry.action@a163f62ae554a8f3cbe27b23db15b60c0ae2e93c # master
              with:
                  attempt_limit: 3
                  action: reactivecircus/android-emulator-runner@50986b1464923454c95e261820bc626f38490ec0
                  with: |
                      api-level: ${{ matrix.api-level }}
                      target: ${{ matrix.target }}
                      arch: ${{ matrix.arch }}
                      force-avd-creation: false
                      emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
                      disable-animations: true
                      script: flutter test integration_test/e2e_tests.dart --flavor emu
            - name: Upload Screenshots
              uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
              with:
                  name: Test result screenshots
                  path: screenshots/*.png

    web:
        runs-on: macos-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
            - name: Emulator cache
              uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
              with:
                  path: ~/.cache/firebase/emulators
                  key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}
            - name: Setup java
              uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
              with:
                  distribution: "temurin"
                  java-version: "17"
            - name: Install Firebase Emulator Suite
              run: npm install -g firebase-tools
            - name: Start firebase emulator
              run: firebase emulators:start &
            - name: Install chromedriver
              uses: nanasess/setup-chromedriver@95301782a076fbe8c9ecf54395a4689f7b195285 # v2.0.0
            - name: Start chromedriver
              run: chromedriver --port=4444 &
            # Set up Flutter.
            - name: Get Flutter version
              id: get-flutter-version
              uses: zgosalvez/github-actions-get-flutter-version-env@7fddf5259c22045dea8dc2f098f494bbd3ca2749 # v2.0.16
            - name: Setup Flutter SDK
              uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
              with:
                  cache: true
                  flutter-version: ${{ steps.get-flutter-version.outputs.version }}
                  channel: stable
            - name: Install Flutter dependencies
              run: flutter pub get
            - name: Run integration tests
              run: flutter drive --driver=integration_test/test_driver/test_driver.dart --target integration_test/e2e_tests.dart -d chrome
            - name: Upload Screenshots
              uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
              with:
                  name: Test result screenshots
                  path: screenshots/*.png
