name: gitleaks
on: [pull_request, push, workflow_dispatch]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

permissions: read-all
jobs:
    scan:
        name: gitleaks
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
              with:
                  fetch-depth: 0
            - uses: gitleaks/gitleaks-action@1f2d10fb689bc07a5f56f48d6db61f5bbbe772fa
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
