name: gitleaks
on: [pull_request, push, workflow_dispatch]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

permissions: read-all
jobs:
    scan:
        name: gitleaks
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
              with:
                egress-policy: audit

            - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
              with:
                  fetch-depth: 0
            - uses: gitleaks/gitleaks-action@1f2d10fb689bc07a5f56f48d6db61f5bbbe772fa
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
