name: Tests
on:
    push:
        branches:
            - main
    pull_request:

# Declare default permissions as read only.
permissions: read-all

jobs:
    unit-test-app:
        name: Unit tests app
        runs-on: macos-latest
        steps:
            # Set up Flutter.
            - name: Clone Flutter repository with stable channel
              uses: subosito/flutter-action@1e6ee87cb840500837bcd50a667fb28815d8e310
              with:
                  cache: true
                  channel: "stable"
            - run: flutter doctor -v

            # Checkout LoveHue code and get packages.
            - name: Checkout LoveHue code
              uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
            - run: flutter pub get -v

            # Create .dev.env file
            - name: Set env
              run: echo '${{ secrets.DEV_ENV }}' > environment/.dev.env

            - name: generate mocks
              run: flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs

            # Analyze, check formatting, and run unit tests.
            - run: flutter analyze
            - name: Ensure the Dart code is formatted correctly
              run: flutter format --set-exit-if-changed --dry-run .
              continue-on-error: true
            - name: Run Flutter unit tests
              run: flutter test --coverage

            - name: Upload to code coverage
              uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70
              with:
                  token: ${{secrets.CODECOV_TOKEN}}
                  file: coverage/lcov.info

    unit-test-functions:
        name: Unit tests cloud functions
        runs-on: macos-latest
        defaults:
            run:
                working-directory: ./functions
        steps:
            - uses: "actions/checkout@v3"

            - uses: "actions/setup-node@v3"
              with:
                  node-version: "16.x"

            - name: "npm build"
              run: "npm ci && npm run build"

            - name: "npm lint"
              run: "npm run lint"

            - name: "npm test"
              run: "npm run test:coverage"

            - name: Upload to code coverage
              uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70
              with:
                  token: ${{secrets.CODECOV_TOKEN}}
                  file: coverage/lcov.info

    # benchmark-test:
    #   name: Benchmark tests
    #   runs-on: ubuntu-18.04
    #   steps:
    #     # Set up Flutter.
    #     - name: Clone Flutter repository with master channel
    #       uses: subosito/flutter-action@1e6ee87cb840500837bcd50a667fb28815d8e310
    #       with:
    #         channel: master
    #     - run: flutter doctor -v
    #     - run: flutter config --enable-web

    #     # Checkout code and get packages.
    #     - name: Checkout code
    #       uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    #     - run: flutter pub get -v

    #     - run: flutter test test_benchmarks

    # golden-test:
    #   name: Golden tests
    #   runs-on: macos-10.15
    #   steps:
    #     # Set up Flutter.
    #     - name: Clone Flutter repository with master channel
    #       uses: subosito/flutter-action@1e6ee87cb840500837bcd50a667fb28815d8e310
    #       with:
    #         channel: master
    #     - run: flutter doctor -v

    #     # Checkout code and get packages.
    #     - name: Checkout code
    #       uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    #     - run: flutter pub get -v

    #     # Run the golden tests and upload failed test artifacts.
    #     - run: flutter test test_goldens
    #     - name: Upload goldens if tests fail
    #       uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
    #       if: failure()
    #       with:
    #         name: goldens
    #         path: test_goldens/failures/
